displayName: API Key Auth
type: middleware

import: github.com/linkphoenix/traefik-api-key-auth

summary: "Authorise API requests with an API Key"
iconPath: .assets/logo.png

testData:
  authenticationHeader: true
  authenticationHeaderName: X-API-KEY
  bearerHeader: true
  bearerHeaderName: Authorization
  removeHeadersOnSuccess: true
  queryParam: false
  queryParamName: token
  pathSegment: false
  keys:
    - 83AB3503-50AA-4B57-9386-B9F0BADF2013
