# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json
# See https://github.com/anthony-spruyt/repo-operator/blob/main/src/templates/.github/workflows/ci.yaml for template comments

name: "CI"
on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"
permissions: {}
jobs:
  lint:
    permissions:
      actions: "read"
      contents: "read"
      security-events: "write"
    uses: "anthony-spruyt/repo-operator/.github/workflows/_lint.yaml@2bb0362170266430d2277de0dde5a204ecbf0eee"
  repo:
    needs:
      - "lint"
    permissions:
      contents: "read"
    uses: "./.github/workflows/ci-repo.yaml"
    secrets: "inherit"
  image:
    needs:
      - "lint"
      - "repo"
    if: "!cancelled() && needs.lint.result == 'success' && (needs.repo.result == 'success' || needs.repo.result == 'skipped')"
    permissions:
      contents: "read"
    uses: "anthony-spruyt/repo-operator/.github/workflows/_images.yaml@2bb0362170266430d2277de0dde5a204ecbf0eee"
    with:
      language: "go"
      test-command: "./scripts/test-image.sh"
  summary:
    needs:
      - "lint"
      - "repo"
      - "image"
    if: "always()"
    permissions:
      actions: "read"
      contents: "read"
    uses: "anthony-spruyt/repo-operator/.github/workflows/_summary.yaml@2bb0362170266430d2277de0dde5a204ecbf0eee"
